### ISSUE TITLE
Getting Started 

### ISSUE THREAD

**Issue by jaykay12** [intermine/similarity#15]
@yochannah I have been following InterMine community for a very long time. I would like to contribute to the organisation.

This project really interests me but I am having no genomic-background in academics.

I have cloned the project and have read the project report from Samyadeep's blog. Can you please tell me the initiating points or some small issues which I can solve to start getting familiar with the codebase.

**Comment by yochannah** [comment]
Hey @jaykay12, and thansk for your offer to help out!

I have a confession if it helps: I have no background in biology either - I'm mostly a computer person ;) Can you tell me a little more about your interests and background? Also feel free to pop into chat.intermine.org if you're around during UK office hours and we can chat that way :) 

One problem we have with this repo is that there aren't really any running docs, so it's a little tricky to reproduce the work - you may have seen the issue in #14. If you're interested in doing some code archaeology and digging about a bit you might be able to see if it's obvious how to load data / run analyses, etc. This could be an incredibly difficult and unrewarding task though, so if you don't feel like it that would be fine! If that's the case, definitely come by chat or email me at yo@intermine.org and we can discuss other ways to get you involved :)

**Comment by jaykay12** [comment]
Yeahh surely @yochannah as of now, I would love to play around with some of the algorithms already implemented by @samyadeepbasu and analysing the data flows through those trial runs only. :smile: 

I am facing a slight problem running the scripts. I am able to run `visualisations.py` but most of the other scripts are failing with traceback like this,

```console
(venv_py2) jaykay12@jalaznith:~/Documents/Github/InterMine/similarity$ python SimRank.py
Traceback (most recent call last):
  File "SimRank.py", line 215, in <module>
    main()
  File "SimRank.py", line 195, in main
    regulatory_graph = get_regulatory_network()
  File "SimRank.py", line 37, in get_regulatory_network
    graph = Graph("http://localhost:7474/db/data/cypher",password="rimo")
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/database/__init__.py", line 327, in __new__
    use_bolt = version_tuple(inst.__remote__.get().content["neo4j_version"]) >= (3,)
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/database/http.py", line 154, in get
    response = self.__base.get(headers=headers, redirect_limit=redirect_limit, **kwargs)
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 966, in get
    return self.__get_or_head("GET", if_modified_since, headers, redirect_limit, **kwargs)
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 943, in __get_or_head
    return rq.submit(redirect_limit=redirect_limit, **kwargs)
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 433, in submit
    http, rs = submit(self.method, uri, self.body, self.headers)
  File "/home/jaykay12/Documents/Github/InterMine/similarity/venv_py2/local/lib/python2.7/site-packages/py2neo/packages/httpstream/http.py", line 362, in submit
    raise SocketError(code, description, host_port=uri.host_port)
py2neo.packages.httpstream.http.SocketError: Connection refused
```

How should I set the connections and the graph database?

**Comment by yochannah** [comment]
@samyadeepbasu I think I'll have to hand this one to you - can you help @jaykay12? :) :+1:

**Comment by samyadeepbasu** [comment]
@jaykay12 So in this script, the data is being loaded from a Neo4j database which was run locally. To get started I would suggest you to try the algorithms on proxy graph data. Load any directed graph and replace the dataset I have used in my implementation(No need of using Neo4j for the time being). Also for every algorithm implemented, there is a corresponding research paper. It might be worthwhile to look into them first before jumping onto the code! I would be happy to have a chat with you about it more if you are interested after 17th!

**Comment by jaykay12** [comment]
Yeahh Thanks alot @samyadeepbasu . A quick chat with you will really help a lot, I will also be slightly busy in some family program till the 20th. I will be going through the research papers as suggested by you once I am free and then we can schedule a chat accordingly as per your convenience.
